name: cinephile
description: cinephile - explanations, twists, community.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  firebase_core: ^2.18.0
  firebase_auth: ^4.6.0
  cloud_firestore: ^4.8.0
  firebase_storage: ^11.0.0
  google_sign_in: ^6.1.0
  flutter_svg: ^2.1.1
  cached_network_image: ^3.2.4
  url_launcher: ^6.2.0
  http: ^1.1.0
  intl: ^0.19.0
  flutter_cache_manager: ^3.3.1
  like_button: ^2.0.5
  image_picker: ^1.1.1
  emoji_picker_flutter: ^2.1.0 
 


 



dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - lib/assets/google.png
    - lib/assets/comment.png
    - lib/assets/heart.png
    - lib/assets/hr.png

    


    


